version: '3'
services:
  postgres:
    image: postgis/postgis
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: docker
    volumes:
      - '/home/desenvolvimento/arquivos/postgres/data_find_my_coffee:/var/lib/postgresql/data'

  app:
    build: .
    command: bash start.sh
    ports:
      - 3001:3000
    volumes:
      - .:/app
      - gems:/gems
    depends_on:
      - postgres

volumes:
  postgres:
  gems: